### ISSUE TITLE
Suggesting Markers

### ISSUE THREAD

**Issue by Ion410901** [lordfiSh/sniperelite5maps#10]
If I want to suggest a marker and I put it in a very accurate location, how long does it take for you to check and put it On the map.

**Comment by Ion410901** [comment]
Also I see there were collectibles for only 3 missions in 2022. It's 2024 now and still only 3 missions with collectibles. Why is that?

**Comment by lordfiSh** [comment]
> If I want to suggest a marker and I put it in a very accurate location, how long does it take for you to check and put it On the map.

Should only take a few minutes to update them. 

> If I want to suggest a marker and I put it in a very accurate location, how long does it take for you to check and put it On the map.
Other Stuff... still on the todo list :-)

**Comment by AtomCrafty** [comment]
@CBernjus and I finished the markers for map 4 + 5 and started with map 6. They've been in the repository for almost half a year now, but apparently the live website hasn't been updated since. @lordfiSh could you take care of that?

Other than that I don't have a lot of time to play the game at the moment, so I don't know when I'll be able to continue populating the remaining maps.

**Comment by Ion410901** [comment]
Also, when do you think you can add the other DLC maps?

**Comment by AtomCrafty** [comment]
I have no plans of buying the second season pass at the moment, considering I haven't even played any of the first season pass' missions. That might change in the future, but I can't make any promises.

**Comment by lordfiSh** [comment]
> I have no plans of buying the second season pass at the moment, considering I haven't even played any of the first season pass' missions. That might change in the future, but I can't make any promises.

I have them, but didn't play them yet. I could invite you again so you can capture them :-) I would do it myself, but only have the Game on Xbox :D

**Comment by AtomCrafty** [comment]
We don't use screenshots for our maps. The textures are extracted straight from the game and rescaled based on parameters captured with a graphics debugger. So I need to load into a map at least once to create the necessary files.

**Comment by AtomCrafty** [comment]
Alright, so it turns out the multiplayer trick won't work because the devs added anticheat since we did it the last time. So I can't join a multiplayer lobby while my capturing setup is injected into the game.

Which ultimately only means I need to get the missions eventually. Not a huge deal, but also not far up on the list of priorities right now. I'll probably do that once the other maps are populated.

**Comment by lordfiSh** [comment]
Update Markers, closing this issue for now.
Commits are welcome.
